INSERT INTO product (name, description, price) VALUES ('iPhone 5', 'A1 lorem1 ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 3590.5);
INSERT INTO product (name, description, price) VALUES ('Smart TV', 'A2lorem ipsum1 dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2190.0);
INSERT INTO product (name, description, price) VALUES ('Macbook Pro', 'A3 Lorem2 ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1250.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer', 'A4 lorem1 ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1200.0);
INSERT INTO product (name, description, price) VALUES ('Rails for Dummies', 'A5 For lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 100.99);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Ex', 'A6 lorem2 ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1350.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer X', 'A7 Lorem2 ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1350.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Alfa', 'A8 Dolor1 sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1850.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Tera', 'A9 Dolor1 sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1950.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Y', 'A10 Dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1700.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Nitro', 'A11 Dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1450.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Card', 'A12 Dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1850.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Plus', 'A13 Dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1350.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Hera', 'A14 Dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2250.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Weed', 'A15 Dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2200.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Max',  'A16 Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2340.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Turbo', 'A17 Ipsum sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1280.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Hot', 'A18 Ipsum sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1450.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Ez', 'A19 Ipsum sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1750.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Tr', 'A20 Ipsum sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1650.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Tx', 'A30 Ipsum sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1680.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Er', 'A31 Ipsumsit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1850.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Min', 'A32 Ipsum sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2250.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Boo', 'A33 Ipsum sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2350.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Foo', 'A34 Ipsum sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 4170.0);

